"""Initial migration

Revision ID: d9c32684e657
Revises: 
Create Date: 2024-09-08 17:18:05.378387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c32684e657'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('history_data',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('param_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('host_operations_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_no', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=255), nullable=False),
    sa.Column('host_no', sa.Integer(), nullable=False),
    sa.Column('dev_eui', sa.String(length=255), nullable=False),
    sa.Column('host_type', sa.String(length=50), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('max_connection', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dev_eui'),
    sa.UniqueConstraint('host_no')
    )
    op.create_table('node_operations_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=255), nullable=False),
    sa.Column('host_no', sa.Integer(), nullable=False),
    sa.Column('dev_eui', sa.String(length=255), nullable=False),
    sa.Column('dev_name', sa.String(length=255), nullable=False),
    sa.Column('dev_type', sa.String(length=50), nullable=False),
    sa.Column('dev_port', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dev_eui')
    )
    op.create_table('substations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=255), nullable=False),
    sa.Column('host_no', sa.Integer(), nullable=False),
    sa.Column('node_no', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('port_no', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.String(length=255), nullable=False),
    sa.Column('drv_type', sa.String(length=50), nullable=False),
    sa.Column('drv_time', sa.Integer(), nullable=False),
    sa.Column('mb_addr', sa.String(length=255), nullable=False),
    sa.Column('mb_param', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substations_system_id'), 'substations', ['system_id'], unique=False)
    op.create_table('super_admins',
    sa.Column('super_admin_id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('super_admin_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('act_time', sa.Integer(), nullable=True),
    sa.Column('act_on_time', sa.Integer(), nullable=True),
    sa.Column('number1', sa.Integer(), nullable=True),
    sa.Column('setup_day', sa.String(), nullable=True),
    sa.Column('repeat_mode', sa.String(), nullable=True),
    sa.Column('interval_day', sa.Integer(), nullable=True),
    sa.Column('act_day', sa.String(), nullable=True),
    sa.Column('cycle_num', sa.Integer(), nullable=True),
    sa.Column('concurrent', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.String(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_system_id'), 'tasks', ['system_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('node_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('param_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('report_name', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('systems',
    sa.Column('system_id', sa.String(length=64), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('admin_password', sa.String(length=256), nullable=False),
    sa.Column('admin_phone_number', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['super_admins.super_admin_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('task_histories',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('task_run_modes',
    sa.Column('mode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('mode_id')
    )
    op.create_table('task_sense_params',
    sa.Column('sense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('high_value', sa.Float(), nullable=False),
    sa.Column('high_act', sa.String(length=20), nullable=False),
    sa.Column('low_value', sa.Float(), nullable=False),
    sa.Column('low_act', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('sense_id')
    )
    op.create_table('task_start_times',
    sa.Column('start_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('begin_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('start_id')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('super_admin_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admins.super_admin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('area_id', sa.String(length=64), nullable=False),
    sa.Column('system_id', sa.String(length=64), nullable=True),
    sa.Column('area_name', sa.String(length=128), nullable=False),
    sa.Column('area_location', sa.String(length=256), nullable=False),
    sa.Column('area_value', sa.Float(), nullable=False),
    sa.Column('area_height', sa.Float(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('background_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('file_token', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_token')
    )
    op.create_index(op.f('ix_background_images_id'), 'background_images', ['id'], unique=False)
    op.create_table('system_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_staff')
    op.drop_index(op.f('ix_background_images_id'), table_name='background_images')
    op.drop_table('background_images')
    op.drop_table('areas')
    op.drop_table('verification_codes')
    op.drop_table('task_start_times')
    op.drop_table('task_sense_params')
    op.drop_table('task_run_modes')
    op.drop_table('task_histories')
    op.drop_table('systems')
    op.drop_table('reports')
    op.drop_table('node_history')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_system_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_substations_system_id'), table_name='substations')
    op.drop_table('substations')
    op.drop_table('nodes')
    op.drop_table('node_operations_logs')
    op.drop_table('hosts')
    op.drop_table('host_operations_logs')
    op.drop_table('history_data')
    op.drop_table('admins')
    # ### end Alembic commands ###
